import { mkdtemp, readFile, rm, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterAll, beforeAll, describe, expect, it } from 'vitest'
import {
  CONTRACT_SPEC,
  videoTranscoderContract,
  type ClipFixtures,
} from '../../application/testing/contracts/videoTranscoderContract'
import { probeFfmpegCapability, type FfmpegPaths } from './ffmpegBinaries'
import { createFfmpegVideoTranscoder, type FfmpegVideoTranscoder } from './ffmpegVideoTranscoder'
import { runProcess } from './runProcess'

/**
 * Ring 3: the real encoder, real files, real subprocesses.
 *
 * The fixtures are **generated by ffmpeg itself** rather than checked in, for the reason
 * the visual baselines are not checked in as JPEGs: a committed 200 kB mp4 is a binary
 * nobody can review, it goes stale against the encoder that reads it, and the three
 * properties that matter here — a rotation matrix, a missing audio track, a 10-bit
 * source — are each one flag on a synthetic clip.
 *
 * `PATH` is read through `process.env` here, which nothing under `src/` outside
 * `env.ts` may do in production — the ban is lifted for test files, and this is the one
 * place it earns the exemption: what is under test *is* the resolution that consumes the
 * value env.ts parses.
 */

// A test file, where `no-restricted-syntax` is off. Production never reads this: env.ts
// parses it once and hands it to the resolver as a value.
const MACHINE_PATH = process.env['PATH'] ?? ''
// Windows needs PATHEXT to find ffmpeg.exe, because `spawn` is never given a shell.
const MACHINE_PATHEXT = process.env['PATHEXT'] ?? ''

const SEARCH = { path: MACHINE_PATH, extensions: MACHINE_PATHEXT }

interface Harness {
  readonly paths: FfmpegPaths
  readonly scratch: string
  readonly transcoder: FfmpegVideoTranscoder
  readonly fixtures: ClipFixtures
}

let harness: Harness

/** Fails loudly rather than skipping: a suite that quietly tests nothing is worse. */
const requireFfmpeg = async (): Promise<FfmpegPaths> => {
  const capability = await probeFfmpegCapability({ search: SEARCH })
  if (!capability.available) {
    throw new Error(
      `this ring-3 suite needs a working ffmpeg: ${capability.reason}. ` +
        `Install one, or run \`npm ci\` so the ffmpeg-static devDependency is present.`,
    )
  }
  return capability.paths
}

/** One generated clip. Everything is synthetic, so nothing here depends on a sample file. */
const generate = async (
  paths: FfmpegPaths,
  directory: string,
  name: string,
  args: readonly string[],
): Promise<Uint8Array> => {
  const file = join(directory, name)
  const result = await runProcess({
    binary: paths.ffmpeg,
    args: ['-nostdin', '-hide_banner', '-loglevel', 'error', '-y', ...args, file],
    timeoutMs: 60_000,
    stallMs: 30_000,
  })
  if (!result.ok) throw new Error(`could not generate ${name}: ${result.stderr}`)
  return new Uint8Array(await readFile(file))
}

const VIDEO_IN = ['-f', 'lavfi', '-i', 'testsrc2=size=320x240:rate=15:duration=1.5']
const AUDIO_IN = ['-f', 'lavfi', '-i', 'sine=frequency=440:duration=1.5']
const H264_OUT = ['-c:v', 'libx264', '-preset', 'ultrafast', '-pix_fmt', 'yuv420p']
const AAC_OUT = ['-c:a', 'aac', '-shortest']

/**
 * A 10-bit source, which is what an iPhone in High Efficiency actually records.
 *
 * HEVC where the build has `libx265`, and 10-bit H.264 otherwise — every `libx264` since
 * 2015 carries both depths in one library. Either one exercises the trap this exists for:
 * without a forced 8-bit output format the encoder happily emits a High 10 stream that
 * transcodes cleanly and shows a black rectangle on the projector.
 */
const tenBitSource = async (paths: FfmpegPaths, directory: string): Promise<Uint8Array> => {
  try {
    return await generate(paths, directory, 'tenbit.mp4', [
      ...VIDEO_IN,
      '-c:v',
      'libx265',
      '-preset',
      'ultrafast',
      '-pix_fmt',
      'yuv420p10le',
      '-tag:v',
      'hvc1',
    ])
  } catch {
    return generate(paths, directory, 'tenbit-h264.mp4', [
      ...VIDEO_IN,
      '-c:v',
      'libx264',
      '-preset',
      'ultrafast',
      '-profile:v',
      'high10',
      '-pix_fmt',
      'yuv420p10le',
    ])
  }
}

/** What ffprobe says one stream of a produced file really is. */
const streamFacts = async (
  paths: FfmpegPaths,
  directory: string,
  bytes: Uint8Array,
): Promise<{ codec: string; pixelFormat: string; profile: string; streams: string[] }> => {
  const file = join(directory, `inspect-${Math.random().toString(16).slice(2)}.mp4`)
  await writeFile(file, bytes)
  const result = await runProcess({
    binary: paths.ffprobe,
    args: [
      '-hide_banner',
      '-loglevel',
      'error',
      // No `-nostdin`: ffprobe has no such option and refuses the whole invocation.
      '-print_format',
      'json',
      '-show_streams',
      `file:${file}`,
    ],
    timeoutMs: 30_000,
    stallMs: 30_000,
  })
  if (!result.ok) throw new Error(`could not inspect the output: ${result.stderr}`)

  const parsed: unknown = JSON.parse(result.stdout)
  const streams =
    typeof parsed === 'object' && parsed !== null && 'streams' in parsed
      ? ((parsed as { streams?: unknown }).streams ?? [])
      : []
  const list = Array.isArray(streams) ? (streams as Record<string, unknown>[]) : []
  const video = list.find((stream) => stream['codec_type'] === 'video') ?? {}

  return {
    codec: String(video['codec_name'] ?? ''),
    pixelFormat: String(video['pix_fmt'] ?? ''),
    profile: String(video['profile'] ?? ''),
    streams: list.map((stream) => String(stream['codec_type'] ?? '')),
  }
}

beforeAll(async () => {
  const paths = await requireFfmpeg()
  const scratch = await mkdtemp(join(tmpdir(), 'eventslide-clip-'))

  const fixtures: ClipFixtures = {
    landscape: await generate(paths, scratch, 'landscape.mp4', [
      ...VIDEO_IN,
      ...AUDIO_IN,
      ...H264_OUT,
      ...AAC_OUT,
    ]),
    /**
     * Landscape frames plus a **display matrix**, which is how every phone records
     * portrait — and the whole point of this fixture.
     *
     * `-display_rotation` as an input option, re-muxed with `-c copy`, is what writes a
     * real `Display Matrix` into `side_data_list` while leaving `streams[].width` and
     * `height` at 320x240. `-metadata:s:v:0 rotate=90` writes a tag some builds no longer
     * read and no longer auto-rotate on, so a fixture built that way would pass the probe
     * assertion through the tag fallback and quietly stop testing the matrix at all.
     */
    portrait: await generate(paths, scratch, 'portrait.mp4', [
      '-display_rotation',
      '90',
      '-i',
      join(scratch, 'landscape.mp4'),
      '-c',
      'copy',
    ]),
    silent: await generate(paths, scratch, 'silent.mp4', [...VIDEO_IN, ...H264_OUT]),
    long: await generate(paths, scratch, 'long.mp4', [
      '-f',
      'lavfi',
      '-i',
      'testsrc2=size=320x240:rate=15:duration=5',
      ...H264_OUT,
    ]),
    notAVideo: new TextEncoder().encode('%PDF-1.7\nthis is not a clip at all\n'),
    // A real container cut off before its `moov` atom: the signature still says mp4, and
    // the header will not parse. A phone that ran out of battery mid-recording.
    corrupt: new Uint8Array(0),
  }

  const truncated = (await generate(paths, scratch, 'whole.mp4', [
    ...VIDEO_IN,
    ...H264_OUT,
  ])).slice(0, 2_048)

  harness = {
    paths,
    scratch,
    transcoder: createFfmpegVideoTranscoder({ paths, scratchRoot: join(scratch, 'work') }),
    fixtures: { ...fixtures, corrupt: truncated },
  }
}, 180_000)

afterAll(async () => {
  harness?.transcoder.close()
  if (harness !== undefined) await rm(harness.scratch, { recursive: true, force: true })
})

videoTranscoderContract('ffmpeg', async () => ({
  transcoder: harness.transcoder,
  fixtures: harness.fixtures,
}))

describe('ffmpegVideoTranscoder against real ffmpeg', () => {
  it('produces H.264 in 8-bit 4:2:0, whatever depth the source was', async () => {
    // The trap, asserted rather than commented: a 10-bit source without a forced output
    // format produces High 10, which transcodes cleanly, passes every check this
    // codebase can make, and renders as a black rectangle on a projector.
    const source = await tenBitSource(harness.paths, harness.scratch)

    const result = await harness.transcoder.transcode(source, CONTRACT_SPEC)

    expect(result.ok).toBe(true)
    if (!result.ok) return
    const facts = await streamFacts(harness.paths, harness.scratch, result.value.video.bytes)
    expect(facts.codec).toBe('h264')
    expect(facts.pixelFormat).toBe('yuv420p')
    expect(facts.profile).not.toContain('10')
  }, 120_000)

  it('keeps nothing but the picture and the sound', async () => {
    // `-map_metadata -1` does not remove streams. An iPhone's `mebx` timed-metadata track
    // carries per-frame gyroscope and sometimes location data, and it is invisible in a
    // player — so the assertion is on the stream list, not on a metadata dump.
    const result = await harness.transcoder.transcode(harness.fixtures.landscape, CONTRACT_SPEC)

    expect(result.ok).toBe(true)
    if (!result.ok) return
    const facts = await streamFacts(harness.paths, harness.scratch, result.value.video.bytes)
    expect(facts.streams.filter((kind) => kind !== 'video' && kind !== 'audio')).toEqual([])
  }, 120_000)

  it('drops the audio stream of a clip that never had one, rather than failing', async () => {
    const result = await harness.transcoder.transcode(harness.fixtures.silent, CONTRACT_SPEC)

    expect(result.ok).toBe(true)
    if (!result.ok) return
    const facts = await streamFacts(harness.paths, harness.scratch, result.value.video.bytes)
    expect(facts.streams).toEqual(['video'])
  }, 120_000)

  it('rotates a portrait clip into its pixels rather than leaving a matrix behind', async () => {
    // ffmpeg auto-rotates on transcode, and that default has moved across releases. This
    // asserts the outcome — a portrait file whose *stored* frames are portrait — instead
    // of trusting a comment about a default.
    const result = await harness.transcoder.transcode(harness.fixtures.portrait, CONTRACT_SPEC)

    expect(result.ok).toBe(true)
    if (!result.ok) return

    const reprobed = await harness.transcoder.probe(result.value.video.bytes)
    expect(reprobed.ok && reprobed.value.dimensions.orientation).toBe('portrait')
    expect(result.value.video.dimensions.orientation).toBe('portrait')
  }, 120_000)

  it('starts the file with its moov atom, so a browser can play before it has it all', async () => {
    // `-movflags +faststart`. Without it the index is at the end and a projector on venue
    // Wi-Fi waits for the whole download before the first frame.
    const result = await harness.transcoder.transcode(harness.fixtures.landscape, CONTRACT_SPEC)

    expect(result.ok).toBe(true)
    if (!result.ok) return

    const head = new TextDecoder('latin1').decode(result.value.video.bytes.slice(0, 512))
    const moov = head.indexOf('moov')
    const mdat = head.indexOf('mdat')
    expect(moov).toBeGreaterThan(-1)
    expect(mdat === -1 || moov < mdat).toBe(true)
  }, 120_000)

  it('leaves no scratch file behind, on the path that fails as well as the one that works', async () => {
    // The thing 1.0 leaked. The scratch root is under MEDIA_ROOT rather than os.tmpdir()
    // because the container is read-only with a tmpfs charged to the memory cgroup.
    const scratchRoot = join(harness.scratch, 'leak-check')
    const transcoder = createFfmpegVideoTranscoder({ paths: harness.paths, scratchRoot })

    await transcoder.transcode(harness.fixtures.landscape, CONTRACT_SPEC)
    await transcoder.transcode(harness.fixtures.corrupt, CONTRACT_SPEC)
    await transcoder.probe(harness.fixtures.landscape)

    const { readdir } = await import('node:fs/promises')
    expect(await readdir(scratchRoot)).toEqual([])
  }, 180_000)

  it('cuts a poster that is a real image of the right size', async () => {
    const result = await harness.transcoder.transcode(harness.fixtures.landscape, CONTRACT_SPEC)

    expect(result.ok).toBe(true)
    if (!result.ok) return
    // JPEG SOI. The poster is what the moderation grid and the album index render.
    expect([...result.value.poster.bytes.slice(0, 3)]).toEqual([0xff, 0xd8, 0xff])
  }, 120_000)

  it('answers a clip whose header will not parse with corrupt, not unsupported', async () => {
    // Two different things to tell a guest: "that is not a video" and "that video is
    // damaged". The signature says mp4, so only the second one is true here.
    expect(harness.transcoder.identify(harness.fixtures.corrupt)).toBe('mp4')
    const probed = await harness.transcoder.probe(harness.fixtures.corrupt)
    expect(!probed.ok && probed.error.code).toBe('clip.corrupt')
  }, 60_000)
})
