/**
 * Opaque, branded identifiers.
 *
 * `EventId` and `PhotoId` are both strings at runtime, but the brand makes them
 * different types at compile time, so `findById(photoId, eventId)` with the arguments
 * swapped does not compile. Given that tenant isolation in this product *is* "did you
 * pass the right event id", that is worth the ceremony.
 *
 * Ids are generated by the `IdGenerator` port (never here — the domain has no
 * randomness) and are opaque: they appear in URLs, so they must not be enumerable the
 * way 1.0's `INTEGER PRIMARY KEY AUTOINCREMENT` was.
 */

declare const brand: unique symbol

export type Branded<T, B extends string> = T & { readonly [brand]: B }

export type EventId = Branded<string, 'EventId'>
export type PhotoId = Branded<string, 'PhotoId'>
export type GuestId = Branded<string, 'GuestId'>
export type UserId = Branded<string, 'UserId'>
export type ReactionId = Branded<string, 'ReactionId'>
/**
 * A queued transcode, not a photo.
 *
 * Separate from `PhotoId` because the two name different things at different times: a
 * `ClipJobId` exists while there is no `photos` row at all, and it is what a guest's
 * phone polls to find out what became of the fifteen seconds they sent. Branding it
 * means the id a guest polls with can never be mistaken for the id of the row the
 * transcode eventually produces.
 */
export type ClipJobId = Branded<string, 'ClipJobId'>
/**
 * One prompt on the host's list — "a selfie with the couple" (docs/ROADMAP.md §2.1).
 *
 * Branded like every other id and for the sharper of the two usual reasons: a guest's
 * phone sends one back on an upload, so this is a **guest-supplied** identifier that
 * decides which row of the host's list a photograph is filed under. The brand is what
 * keeps the value that arrived in a multipart field from being passed anywhere a
 * `PhotoId` belongs, and the repository that reads it takes an `EventId` first.
 */
export type MissionId = Branded<string, 'MissionId'>
/**
 * One shared gallery link (docs/ROADMAP.md §4.1).
 *
 * Distinct from the link's **token**, and the distinction is the design: the token is the
 * secret a host sends to their guests and is never stored, only its digest; this id is the
 * row's name, and it is what a signed media URL carries, so a URL copied out of an `<img>`
 * names the link without handing out the key to it.
 */
export type ShareLinkId = Branded<string, 'ShareLinkId'>

/**
 * The only casts in the codebase. Use them at a boundary — a database row becoming an
 * entity, a parsed request becoming domain input — never inside domain logic.
 */
export const asEventId = (value: string): EventId => value as EventId
export const asPhotoId = (value: string): PhotoId => value as PhotoId
export const asGuestId = (value: string): GuestId => value as GuestId
export const asUserId = (value: string): UserId => value as UserId
export const asReactionId = (value: string): ReactionId => value as ReactionId
export const asClipJobId = (value: string): ClipJobId => value as ClipJobId
export const asMissionId = (value: string): MissionId => value as MissionId
export const asShareLinkId = (value: string): ShareLinkId => value as ShareLinkId
