/**
 * Opaque, branded identifiers.
 *
 * `EventId` and `PhotoId` are both strings at runtime, but the brand makes them
 * different types at compile time, so `findById(photoId, eventId)` with the arguments
 * swapped does not compile. Given that tenant isolation in this product *is* "did you
 * pass the right event id", that is worth the ceremony.
 *
 * Ids are generated by the `IdGenerator` port (never here — the domain has no
 * randomness) and are opaque: they appear in URLs, so they must not be enumerable the
 * way 1.0's `INTEGER PRIMARY KEY AUTOINCREMENT` was.
 */

declare const brand: unique symbol

export type Branded<T, B extends string> = T & { readonly [brand]: B }

export type EventId = Branded<string, 'EventId'>
export type PhotoId = Branded<string, 'PhotoId'>
export type GuestId = Branded<string, 'GuestId'>
export type UserId = Branded<string, 'UserId'>
export type ReactionId = Branded<string, 'ReactionId'>

/**
 * The only casts in the codebase. Use them at a boundary — a database row becoming an
 * entity, a parsed request becoming domain input — never inside domain logic.
 */
export const asEventId = (value: string): EventId => value as EventId
export const asPhotoId = (value: string): PhotoId => value as PhotoId
export const asGuestId = (value: string): GuestId => value as GuestId
export const asUserId = (value: string): UserId => value as UserId
export const asReactionId = (value: string): ReactionId => value as ReactionId
