/**
 * The part of the upgrade policy (`docs/UPGRADING.md`) that a CHANGELOG can be held to.
 *
 * The policy says a major is the only release that breaks something, and that it never does
 * so silently: its entry has a `BREAKING` section, and `docs/UPGRADING.md` has an
 * `Upgrading to N.0` section for it. A minor or a patch has neither. This reads a CHANGELOG
 * and an UPGRADING page as text and names every place they disagree with that.
 *
 * Text in, problems out, and no file read here, so a test can feed it a CHANGELOG that
 * breaks the rule and watch it be named. The one that reads the real files is
 * `scripts/changelogPolicy.test.ts`.
 */

/** The version of an entry heading, `## [3.0.0] - 2026-11-01`, and what the entry carries. */
export interface ChangelogEntry {
  readonly version: string
  readonly major: number
  /** The text of every `### ` heading in the entry, in order. */
  readonly sections: readonly string[]
}

/**
 * An entry heading: a version in brackets, then whatever follows. `## [3.0.0] - 2026-11-01` is
 * how this file writes it; release-please writes `## [3.0.0](compare-url) (2026-11-01)`. The
 * date is `scripts/releaseVersion.test.ts`'s to check, not this file's.
 */
const ENTRY_HEADING = /^## \[(\d+)\.(\d+)\.(\d+)\]/

/**
 * A `BREAKING` section, hand-written (`### BREAKING`) or generated by release-please
 * (`### ⚠ BREAKING CHANGES`): the word, after anything that is not a letter.
 */
const BREAKING_SECTION = /^\W*BREAKING\b/

/** The lines of a CHANGELOG outside the fenced code blocks, which can hold any heading. */
const unfencedLines = (changelog: string): readonly string[] => {
  let fenced = false
  return changelog.split('\n').filter((line) => {
    if (line.startsWith('```')) {
      fenced = !fenced
      return false
    }
    return !fenced
  })
}

/**
 * The entries of a CHANGELOG, newest first, as they stand in the file.
 *
 * Only a heading of the form `## [X.Y.Z]` is an entry. The preamble and a heading like
 * `## 2.0.0 (never tagged)` are not, and neither is anything inside a fenced code block. A
 * heading that opens with `## [` and is not an entry either is named by
 * {@link unreadableHeadings}.
 */
export const parseEntries = (changelog: string): readonly ChangelogEntry[] => {
  const entries: { version: string; major: number; sections: string[] }[] = []
  let current: (typeof entries)[number] | null = null

  for (const line of unfencedLines(changelog)) {
    const heading = ENTRY_HEADING.exec(line)
    if (heading !== null) {
      current = {
        version: `${heading[1]}.${heading[2]}.${heading[3]}`,
        major: Number(heading[1]),
        sections: [],
      }
      entries.push(current)
    } else if (line.startsWith('## ')) {
      current = null
    } else if (current !== null && line.startsWith('### ')) {
      current.sections.push(line.slice(4).trim())
    }
  }
  return entries
}

/**
 * The `## [...]` headings that are not entries: `## [Unreleased]`, `## [3.0.0-rc.1]`, `## [3.0]`.
 *
 * They are named rather than skipped, because a heading this cannot read is an entry nobody
 * judges: a major written as `## [3.0.0-rc.1]` would pass the policy by not being seen.
 */
export const unreadableHeadings = (changelog: string): readonly string[] =>
  unfencedLines(changelog).filter(
    (line) => line.startsWith('## [') && ENTRY_HEADING.exec(line) === null,
  )

const hasBreakingSection = (entry: ChangelogEntry): boolean =>
  entry.sections.some((section) => BREAKING_SECTION.test(section))

/** Whether `upgrading` has a `## Upgrading to N.0` heading for this major. */
const hasUpgradingSection = (upgrading: string, major: number): boolean =>
  new RegExp(`^## Upgrading to ${major}\\.0\\b`, 'm').test(upgrading)

/**
 * Every way `changelog` and `upgrading` break the policy, one sentence each; empty when
 * neither does.
 *
 * An entry is judged against the one below it, the release it follows. The oldest entry
 * follows nothing the file can show, so it is not judged.
 */
export const policyProblems = (changelog: string, upgrading: string): readonly string[] => {
  const entries = parseEntries(changelog)
  const problems: string[] = unreadableHeadings(changelog).map(
    (heading) => `the heading "${heading}" is not an entry ("## [X.Y.Z]"), so it is not judged`,
  )

  entries.forEach((entry, index) => {
    const previous = entries[index + 1]
    if (previous === undefined) return

    if (entry.major > previous.major) {
      if (!hasBreakingSection(entry)) {
        problems.push(
          `${entry.version} is a major (it follows ${previous.version}) and has no BREAKING section`,
        )
      }
      if (!hasUpgradingSection(upgrading, entry.major)) {
        problems.push(
          `${entry.version} is a major and docs/UPGRADING.md has no "## Upgrading to ${entry.major}.0" section`,
        )
      }
    } else if (hasBreakingSection(entry)) {
      problems.push(
        `${entry.version} has a BREAKING section but follows ${previous.version} in the same major: only a major may break something`,
      )
    }
  })

  return problems
}
